In [2]:
import torch

标量由一个元素的张量表示。

In [3]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

**向量**是由标量组成的列表

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一个元素

In [5]:
x[3]

tensor(3)

访问张量的长度。

In [6]:
len(x)  # 如果张量的轴为2，则len()返回第一个轴的长度

4

In [8]:
x.shape  # 只有一个轴的张量

torch.Size([4])

可以通过两个分量m和n，创建一个形状为`m*n`的矩阵。

In [9]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
A.T  # 矩阵的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵：关于主对角线对称。A等于其转置。即A = A<sup>T</sup>

In [12]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

创建轴为3的张量

In [15]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定相同shape的任何两个张量，按元素二元运算的结果是相同shape的张量。

In [19]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 创建一个新的张量，重新分配一块新的内存。
print(B)
print(id(A))
print(id(B))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
1708698644800
1708689734784


**两个矩阵按照元素乘法**

In [20]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [22]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a * X  # 将标量a与每个元素相乘

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

**对张量根据某个轴进行求和**

In [23]:
x = torch.arange(4, dtype=torch.float32)
print(x)
print(x.sum())  # 对所有元素求和

tensor([0., 1., 2., 3.])
tensor(6.)


In [27]:
A.shape, A.sum()  # 默认是计算所有的元素和。

(torch.Size([5, 4]), tensor(190.))

In [29]:
print(A)
# shape = (5, 4) 计算第1维度的元素的和，即5行，每一行的和。axis=0是行之间的操作。
# 第一列的所有行相加为第一个元素。
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [32]:
print(A)
# 对（5,4）的第二维度进行求和，4列。axis=0是列之间的操作
# 第一行的所有列相加，是第一个元素。
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

**求张量的平均值**

In [33]:
A.mean(), A.sum() / A.numel()  # tensor.numel() 返回元素的个数

(tensor(9.5000), tensor(9.5000))

In [35]:
# 按照某个维度进行求均值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

**计算总和或均值时保持轴数不变**

In [37]:
sum_A = A.sum(axis=1,)
print(sum_A)
sum_B = A.sum(axis=1, keepdims=True)  # keepdims保持轴数不变，默认False
print(sum_B)

tensor([ 6., 22., 38., 54., 70.])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [40]:
# 通过广播机制将A 除以sum_B。  此时第一行都除以6，第二行都除以22。
print(A)
A / sum_B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [47]:
# 进行累加求和。

# 根据某个轴累加求和。dim必填参数。dim=0为进行行操作。
# 第一列的所有行进行累加。 0 0 + 4 0 + 4 + 8 。。。
A.cumsum(dim=0)  


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

**点积。即相同位置元素相乘，然后相加**

In [50]:
x = torch.tensor([1,2,3,5], dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)  # dot 向量的点积

(tensor([1., 2., 3., 5.]), tensor([1., 1., 1., 1.]), tensor(11.))

In [51]:
# 也可以通过进行按元素相乘，然后相加，计算点积。
torch.sum(x * y)

tensor(11.)

**矩阵乘以向量。结果为一个向量。**

In [57]:
print(A)
print(x)
A.shape, x.shape, torch.mv(A, x)  # mv是矩阵和向量的乘积

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([1., 2., 3., 5.])


(torch.Size([5, 4]), torch.Size([4]), tensor([ 23.,  67., 111., 155., 199.]))

**矩阵乘以矩阵**

In [59]:
print(A)
B = torch.ones(4, 3)
print(B)
torch.mm(A, B)  # 两个矩阵相乘，A的行乘以B的列。

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

**L2向量范数。向量元素平方和的平方根**

In [60]:
u = torch.tensor([3.0, 4.0])
torch.norm(u)  # L2范数

tensor(5.)

**L1范数。向量元素的绝对值之和**

In [61]:
print(u)
torch.abs(u).sum()

tensor([3., 4.])


tensor(7.)

In [62]:
x1 = torch.tensor([[-3, 4], [2, -7]])
print(x1)
x1.abs()

tensor([[-3,  4],
        [ 2, -7]])


tensor([[3, 4],
        [2, 7]])

**矩阵的F范数。矩阵元素的平方和的平方根**

In [63]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 拓展 - 按特定轴相加问题

In [64]:
a = torch.ones((2, 5, 4))
a.shape

torch.Size([2, 5, 4])

In [65]:
# 如果 对axis=1进行相加。则结果的shape为[2, 4]
a.sum(axis=1).shape

torch.Size([2, 4])

In [66]:
# 如果按照axis=0进行相加，结果shape为[5, 4]
a.sum(axis=0).shape

torch.Size([5, 4])

In [67]:
# 如果按照axis=[0,1]进行相加，结果shape为[4]
a.sum(axis=[0, 1]).shape

torch.Size([4])

In [69]:
# 如果使用keepdims=True参数。则结果原来的shape，变为1
a.sum(axis=1, keepdims=True).shape

torch.Size([2, 1, 4])